spring.application.name=deal
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/deal_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=false

# Logging
logging.level.com.example.deal=DEBUG
logging.level.org.springframework.web=INFO
logging.level.liquibase=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# Calculator service URL
calculator.url=http://localhost:8080

# OpenAPI (SpringDoc)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Actuator
management.endpoints.web.exposure.include=health,info,metrics