spring.application.name=deal
server.port=${DEAL_PORT:8081}

# Database
spring.datasource.url=${URL_DB:jdbc:postgresql://postgres:5432/deal_db}
spring.datasource.username=${USER_DB:postgres}
spring.datasource.password=${PASSWORD_DB:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.drop-first=false

# Logging
logging.level.com.example.deal=DEBUG
logging.level.org.springframework.web=INFO
logging.level.liquibase=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# Calculator service URL
calculator.url=${CALCULATOR_ADDRESS:http://calculator:8080}

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer