spring.application.name=calculator-service

server.port=8080

#Настройки для кредитного калькуляторв
credit.calculator.baseRate=15.0
credit.calculator.insurance.discount=3.0
credit.calculator.insurance.cost-per-million=100000
credit.calculator.salary.discount=1.0

logging.level.com.example.calculator=DEBUG
