server.port=${DOSSIER_PORT:8082}

spring.kafka.bootstrap-servers=${KAFKA_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=dossier-group-new-3
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=EmailMessage:com.example.deal.dto.EmailMessage

logging.level.org.springframework.kafka=INFO

# Mail 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Logging
logging.level.com.example.dossier=DEBUG


logging.level.org.springframework.kafka=TRACE
logging.level.org.apache.kafka=TRACE

spring.main.allow-bean-definition-overriding=true