server.port=8082

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=dossier-group-new-3
spring.kafka.consumer.auto-offset-reset=earliest

logging.level.org.springframework.kafka=INFO

# Mail (явные значения, без переменных)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Logging
logging.level.com.example.dossier=DEBUG


logging.level.org.springframework.kafka=TRACE
logging.level.org.apache.kafka=TRACE

spring.main.allow-bean-definition-overriding=true